# fly.toml app configuration file generated for javascript-bot on 2023-12-10T13:42:25+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "javascript-bot"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]

